/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as CoordenadorRouteImport } from './routes/coordenador'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessorIndexRouteImport } from './routes/professor.index'
import { Route as CoordenadorIndexRouteImport } from './routes/coordenador.index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as ProfessorRelatorioRouteImport } from './routes/professor.relatorio'
import { Route as ProfessorCategoriasRouteImport } from './routes/professor.categorias'
import { Route as ProfessorAlunosRouteImport } from './routes/professor.alunos'
import { Route as CoordenadorProfessoresRouteImport } from './routes/coordenador.professores'
import { Route as CoordenadorCursosRouteImport } from './routes/coordenador.cursos'
import { Route as AlunoPerfilRouteImport } from './routes/aluno.perfil'
import { Route as AlunoNovoRouteImport } from './routes/aluno.novo'
import { Route as AlunoCertificadosRouteImport } from './routes/aluno.certificados'

const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordenadorRoute = CoordenadorRouteImport.update({
  id: '/coordenador',
  path: '/coordenador',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorIndexRoute = ProfessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessorRoute,
} as any)
const CoordenadorIndexRoute = CoordenadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoordenadorRoute,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const ProfessorRelatorioRoute = ProfessorRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorCategoriasRoute = ProfessorCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorAlunosRoute = ProfessorAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => ProfessorRoute,
} as any)
const CoordenadorProfessoresRoute = CoordenadorProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => CoordenadorRoute,
} as any)
const CoordenadorCursosRoute = CoordenadorCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => CoordenadorRoute,
} as any)
const AlunoPerfilRoute = AlunoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoNovoRoute = AlunoNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoCertificadosRoute = AlunoCertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => AlunoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/coordenador': typeof CoordenadorRouteWithChildren
  '/professor': typeof ProfessorRouteWithChildren
  '/aluno/certificados': typeof AlunoCertificadosRoute
  '/aluno/novo': typeof AlunoNovoRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/coordenador/cursos': typeof CoordenadorCursosRoute
  '/coordenador/professores': typeof CoordenadorProfessoresRoute
  '/professor/alunos': typeof ProfessorAlunosRoute
  '/professor/categorias': typeof ProfessorCategoriasRoute
  '/professor/relatorio': typeof ProfessorRelatorioRoute
  '/aluno/': typeof AlunoIndexRoute
  '/coordenador/': typeof CoordenadorIndexRoute
  '/professor/': typeof ProfessorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluno/certificados': typeof AlunoCertificadosRoute
  '/aluno/novo': typeof AlunoNovoRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/coordenador/cursos': typeof CoordenadorCursosRoute
  '/coordenador/professores': typeof CoordenadorProfessoresRoute
  '/professor/alunos': typeof ProfessorAlunosRoute
  '/professor/categorias': typeof ProfessorCategoriasRoute
  '/professor/relatorio': typeof ProfessorRelatorioRoute
  '/aluno': typeof AlunoIndexRoute
  '/coordenador': typeof CoordenadorIndexRoute
  '/professor': typeof ProfessorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRouteWithChildren
  '/coordenador': typeof CoordenadorRouteWithChildren
  '/professor': typeof ProfessorRouteWithChildren
  '/aluno/certificados': typeof AlunoCertificadosRoute
  '/aluno/novo': typeof AlunoNovoRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/coordenador/cursos': typeof CoordenadorCursosRoute
  '/coordenador/professores': typeof CoordenadorProfessoresRoute
  '/professor/alunos': typeof ProfessorAlunosRoute
  '/professor/categorias': typeof ProfessorCategoriasRoute
  '/professor/relatorio': typeof ProfessorRelatorioRoute
  '/aluno/': typeof AlunoIndexRoute
  '/coordenador/': typeof CoordenadorIndexRoute
  '/professor/': typeof ProfessorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/coordenador'
    | '/professor'
    | '/aluno/certificados'
    | '/aluno/novo'
    | '/aluno/perfil'
    | '/coordenador/cursos'
    | '/coordenador/professores'
    | '/professor/alunos'
    | '/professor/categorias'
    | '/professor/relatorio'
    | '/aluno/'
    | '/coordenador/'
    | '/professor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aluno/certificados'
    | '/aluno/novo'
    | '/aluno/perfil'
    | '/coordenador/cursos'
    | '/coordenador/professores'
    | '/professor/alunos'
    | '/professor/categorias'
    | '/professor/relatorio'
    | '/aluno'
    | '/coordenador'
    | '/professor'
  id:
    | '__root__'
    | '/'
    | '/aluno'
    | '/coordenador'
    | '/professor'
    | '/aluno/certificados'
    | '/aluno/novo'
    | '/aluno/perfil'
    | '/coordenador/cursos'
    | '/coordenador/professores'
    | '/professor/alunos'
    | '/professor/categorias'
    | '/professor/relatorio'
    | '/aluno/'
    | '/coordenador/'
    | '/professor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRouteWithChildren
  CoordenadorRoute: typeof CoordenadorRouteWithChildren
  ProfessorRoute: typeof ProfessorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordenador': {
      id: '/coordenador'
      path: '/coordenador'
      fullPath: '/coordenador'
      preLoaderRoute: typeof CoordenadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/': {
      id: '/professor/'
      path: '/'
      fullPath: '/professor/'
      preLoaderRoute: typeof ProfessorIndexRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/coordenador/': {
      id: '/coordenador/'
      path: '/'
      fullPath: '/coordenador/'
      preLoaderRoute: typeof CoordenadorIndexRouteImport
      parentRoute: typeof CoordenadorRoute
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/professor/relatorio': {
      id: '/professor/relatorio'
      path: '/relatorio'
      fullPath: '/professor/relatorio'
      preLoaderRoute: typeof ProfessorRelatorioRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/categorias': {
      id: '/professor/categorias'
      path: '/categorias'
      fullPath: '/professor/categorias'
      preLoaderRoute: typeof ProfessorCategoriasRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/alunos': {
      id: '/professor/alunos'
      path: '/alunos'
      fullPath: '/professor/alunos'
      preLoaderRoute: typeof ProfessorAlunosRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/coordenador/professores': {
      id: '/coordenador/professores'
      path: '/professores'
      fullPath: '/coordenador/professores'
      preLoaderRoute: typeof CoordenadorProfessoresRouteImport
      parentRoute: typeof CoordenadorRoute
    }
    '/coordenador/cursos': {
      id: '/coordenador/cursos'
      path: '/cursos'
      fullPath: '/coordenador/cursos'
      preLoaderRoute: typeof CoordenadorCursosRouteImport
      parentRoute: typeof CoordenadorRoute
    }
    '/aluno/perfil': {
      id: '/aluno/perfil'
      path: '/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof AlunoPerfilRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/novo': {
      id: '/aluno/novo'
      path: '/novo'
      fullPath: '/aluno/novo'
      preLoaderRoute: typeof AlunoNovoRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/certificados': {
      id: '/aluno/certificados'
      path: '/certificados'
      fullPath: '/aluno/certificados'
      preLoaderRoute: typeof AlunoCertificadosRouteImport
      parentRoute: typeof AlunoRoute
    }
  }
}

interface AlunoRouteChildren {
  AlunoCertificadosRoute: typeof AlunoCertificadosRoute
  AlunoNovoRoute: typeof AlunoNovoRoute
  AlunoPerfilRoute: typeof AlunoPerfilRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoCertificadosRoute: AlunoCertificadosRoute,
  AlunoNovoRoute: AlunoNovoRoute,
  AlunoPerfilRoute: AlunoPerfilRoute,
  AlunoIndexRoute: AlunoIndexRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

interface CoordenadorRouteChildren {
  CoordenadorCursosRoute: typeof CoordenadorCursosRoute
  CoordenadorProfessoresRoute: typeof CoordenadorProfessoresRoute
  CoordenadorIndexRoute: typeof CoordenadorIndexRoute
}

const CoordenadorRouteChildren: CoordenadorRouteChildren = {
  CoordenadorCursosRoute: CoordenadorCursosRoute,
  CoordenadorProfessoresRoute: CoordenadorProfessoresRoute,
  CoordenadorIndexRoute: CoordenadorIndexRoute,
}

const CoordenadorRouteWithChildren = CoordenadorRoute._addFileChildren(
  CoordenadorRouteChildren,
)

interface ProfessorRouteChildren {
  ProfessorAlunosRoute: typeof ProfessorAlunosRoute
  ProfessorCategoriasRoute: typeof ProfessorCategoriasRoute
  ProfessorRelatorioRoute: typeof ProfessorRelatorioRoute
  ProfessorIndexRoute: typeof ProfessorIndexRoute
}

const ProfessorRouteChildren: ProfessorRouteChildren = {
  ProfessorAlunosRoute: ProfessorAlunosRoute,
  ProfessorCategoriasRoute: ProfessorCategoriasRoute,
  ProfessorRelatorioRoute: ProfessorRelatorioRoute,
  ProfessorIndexRoute: ProfessorIndexRoute,
}

const ProfessorRouteWithChildren = ProfessorRoute._addFileChildren(
  ProfessorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRouteWithChildren,
  CoordenadorRoute: CoordenadorRouteWithChildren,
  ProfessorRoute: ProfessorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
